apiVersion: v1
kind: Secret
metadata:
  name: gnx-app-secrets
  namespace: gnx-apps

type: Opaque
data:
  MONGODB_CONNECTION_STRING: ZmlsbF9pdF9pbg==
  RABBITMQ_HOST_NAME: ZmlsbF9pdF9pbg==
  RABBITMQ_VIRTUAL_HOST: ZmlsbF9pdF9pbg==
  RABBITMQ_USER_NAME: ZmlsbF9pdF9pbg==
  RABBITMQ_PASSWORD: ZmlsbF9pdF9pbg==
