apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhY3Jwcm9nZXR0b3ZlZ2FkZXYuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6ImFjclByb2dldHRvVmVnYURFViIsInBhc3N3b3JkIjoiZUlhQ2x3S1JtcytCL2RRQSttektua2V6VGUvbktNRFJQWTgzZWRLZUZBK0FDUkJCRTV0cSIsImVtYWlsIjoiZ2lvdmFubmkubm9jY29AYmV0YTgwZ3JvdXAuaXQiLCJhdXRoIjoiWVdOeVVISnZaMlYwZEc5V1pXZGhSRVZXT21WSllVTnNkMHRTYlhNclFpOWtVVUVyYlhwTGJtdGxlbFJsTDI1TFRVUlNVRms0TTJWa1MyVkdRU3RCUTFKQ1FrVTFkSEU9In19fQ==
