apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: <<your-docker-config-json>>
# Note: Replace <<your-docker-config-json>> with the base64 encoded content of your Docker config file.
