# identities-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identities
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }} # Number of pods to run
  selector:
    matchLabels:
      app: identities # Select pods with this label
  template:
    metadata:
      labels:
        app: identities # Label for the pods
    spec:
      containers:
        - name: identities-container
          image: "genocs/identities-webapi:{{ .Values.imageTag.identities }}"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: logger__level
              value: "Debug"

            # RabbitMQ
            - name: rabbitmq__hostname
              value: {{ .Values.rabbitmq.hostname }}
            - name: rabbitmq__hostnames__0
              value: {{ .Values.rabbitmq.hostname }}
            - name: rabbitmq__virtualhost
              value: {{ .Values.rabbitmq.virtualhost }}
            - name: rabbitmq__username
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_USER_NAME
            - name: rabbitmq__password
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_PASSWORD

            # MongoDB
            - name: mongodb__connectionString
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_CONNECTION_STRING

          ports:
            - containerPort: 8080 # Port the container exposes
          resources: # Optional resource requests and limits
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi
