apiVersion: v1
kind: ConfigMap
metadata:
  name: python-web-app-config
  labels:
    app: python-web-app
data:
  ENVIRONMENT: "production"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8080"
  LOG_LEVEL: "INFO"
