apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: myapp
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis-master:6379
    - name: redisPassword
      value: ""
    - name: enableTLS
      value: "false"
