apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: myapp
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
#     annotations:
#       dapr.io/enabled: "true"
#       dapr.io/app-id: "sample-app"
#       dapr.io/app-port: "3000"
    spec:
      containers:
        - name: sample-app
          image: node:16-alpine
          command: ["sh", "-c"]
          args:
            - |
              apk add --no-cache curl
              while true; do
                echo "Sample app running..."
                sleep 30
              done
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: myapp
spec:
  selector:
    app: sample-app
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
