apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    enabled: true
    expandParams: true
    includeBody: true
    samplingRate: 100
    zipkin:
      endpoint: http://zipkin.default.svc.cluster.local:9411/api/v2/spans