apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: zipkin
  namespace: myapp
spec:
  type: exporters.zipkin
  version: v1
  metadata:
    - name: enabled
      value: "true"
    - name: esporterAddress
      value: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"