apiVersion: v1
kind: Service
 
metadata:
  name: auth-service
  namespace: gnx-apps
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    run: auth-webapi
 
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-port-generic
      port: 80
      targetPort: 8080
  selector:
    run: auth-webapi